# Docker compose configuration for development environment
# Spring Boot application is run locally and uses Spring Boot Docker Compose plugin to spin up service containers

services:
  postgres:
    image: 'postgres:17-alpine'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - '5432:5432'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
  elasticsearch:
    image: 'elasticsearch:9.0.3'
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    volumes:
      - 'elasticsearch-data:/usr/share/elasticsearch/data'
volumes:
  postgres-data:
  elasticsearch-data:
